replicaCount: 1

image:
  repository: 160728044875.dkr.ecr.eu-central-1.amazonaws.com/wiliot-init
  pullPolicy: IfNotPresent
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 8080

resources:
   limits:
     cpu: 50m
     memory: 64Mi
   requests:
     cpu: 50m
     memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
